import Sidebar from "@/components/Sidebar"
import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { SwapiDataProvider } from "@/context/DataContext"
import Navbar from "@/components/Navbar"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SwapiDataProvider>
          <Navbar />
          <Sidebar />
          {children}
        </SwapiDataProvider>
      </body>
    </html>
  )
}
